### ISSUE TITLE
Create a powerful class to work with SQL query

### ISSUE THREAD

**Issue by tadeubarbosa** [valdiney/Ofir_Framework#41]
The task has been called in [README](https://github.com/valdiney/Ofir_Framework-0.1/blob/master/README.md#what-i-need-at-this-moment).

#### Description
"I need to create a powerful class to work with SQL query. My objective is abstracting the SQL language in the Application."

**Comment by rafamttz** [comment]
Hi, can you explain in a better way, or give me a example of abstracting you can get. I'm interested to help you.

**Comment by tadeubarbosa** [comment]
Hi! So... We need to create a class to provide us manipulation of database from our services.

For example:
```php
// sources/models/Users.php
...
protected $table = "users";
public function all() {
  $users = $this->model->getAll();
  ...
  return $users;
}
```

Well, this will ease of for use it. A class to provide access to database and manipulate SQL.

**Comment by valdiney** [comment]
Now Ofir use the Eloquent ORM
